# Generated by Django 5.2.4 on 2025-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jop_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Full Time', 'Part Time')], max_length=15),
        ),
    ]
